#!/bin/sh
# common instructions for both bash and zshrc

export PYTHONRC="$HOME/.pythonrc"

export PYTHONIOENCODING=utf-8

export PATH=$HOME/.nmap:$HOME/bin-scripts:$HOME/bin:$HOME/.local/bin:$HOME/.cargo/bin:$HOME/workspace/0_src/esp-open-sdk/xtensa-lx106-elf/bin:$PATH
export MANPATH=`manpath`:$HOME/.nmap/docs # add a symlink to man1 there
alias nmapp='nmap --script="default,external,safe and not http-slowloris-check"'
alias nconf='./configure --without-ndiff --without-zenmap  --without-nping --without-ncat --without-nmap-update'

alias killbg='for job in `jobs -l | egrep -o "([0-9][0-9]+)"`; do kill $job ; done'
alias sort='LC_ALL=C sort'

if [[ $TERM == screen ]]; then
echo "Jestes w screenie"
fi

if [ -f ~/.github-token ]; then
  source ~/.github-token
fi

export VIRTUAL_ENV_DISABLE_PROMPT=1
if [ -f ~/virtualenv/bin/activate ]; then
    source ~/virtualenv/bin/activate
fi

export LC_ALL=en_US.UTF-8

# If there is Nmap installed but it has no cap_net_raw for me.
if nvim --version >/dev/null 2>&1; then
  alias vim=nvim
  export EDITOR=`which nvim`
else
  export EDITOR=`which vim`
  vim --version >/dev/null 2>&1 || echo "No vim found."
fi

if nmap --version >/dev/null && getcap `which nmap` 2>/dev/null | grep -q cap_net_raw; then
  export NMAP_PRIVILEGED="1"
else
  echo "WARNING: No Nmap with cap_net_raw in \$PATH!" >&2
fi


if hub --version >/dev/null 2>&1; then
    if ! git --version | grep -q hub; then
      alias git=hub
    fi
fi

alias mow='rlwrap espeak -v pl'
alias nmap-quiet='nmap -Pn -n'
alias shred-zero='shred -uvzn0'

export AFL_SKIP_CPUFREQ=1
export AFL_EXIT_WHEN_DONE=1

alias datep="date | tr ' ' '-'"

export PYTHONSTARTUP=~/.pythonrc
export SUDO_PROMPT="[sudo] password `whoami`@`hostname`: "
export LD_LIBRARY_PATH=/home/d33tah/lib

# Disable bell for less
export PAGER='less -q'

function gen_words() {
    LC_ALL="$1" aspell dump master  | iconv -f latin2 -t utf-8 | cut -d'/' -f1
};

function gen_pass() {
    sort -R <( gen_words "pl" ) <( gen_words "en_US" ) | uniq | tail -n30
}

export GOPATH=$HOME/GOPATH
export PATH=~/workspace/go/bin:$PATH::$GOPATH/bin:/home/d33tah/workspace/src/osxcross/target/bin
export PKG_CONFIG_PATH=$HOME/lib/pkgconfig

P=~/workspace/profound
H=~/workspace/hakierspejs

alias vi=/usr/local/bin/nvim
alias vim=/usr/local/bin/nvim
