#!/usr/bin/env python

"""
Converts the standard input from the CSV format to tab-delimited one and prints
the converted output. Fails if any column contains the tab character before
conversion.

Author: Jacek Wielemborek, licensed under WTFPL.
"""

import csv
import sys

if sys.stdin.isatty():
    sys.exit("USAGE: %s < input" % sys.argv[0])

r = csv.reader(sys.stdin)
for row in r:
    for col in row:
        if '\t' in col:
            sys.exit("The column contains the delimiter.")
    print('\t'.join(list(row)))
