#!/usr/bin/env python

"""
Converts the standard input from the CSV format to tab-delimited one and prints
the converted output. Fails if any column contains the tab character before
conversion.

Author: Jacek Wielemborek, licensed under WTFPL.
"""

import csv
import sys

if sys.stdin.isatty():
    sys.exit("USAGE: %s < input" % sys.argv[0])

add_null = "--add-null" in sys.argv
remove_tabs = "--remove-tabs" in sys.argv

r = csv.reader(sys.stdin)
for row in r:
    for i in range(len(row)):
        if '\t' in row[i]:
            if not remove_tabs:
                sys.exit("The column contains the delimiter.")
            else:
                row[i] = row[i].replace('\t', '')
        if row[i] == '' and add_null:
            row[i] = '\\N'
    print('\t'.join(list(row)))
