#!/bin/bash

# Loads the given program in a GNU debugger session, sets a breakpoint at
# main() and runs the program. Useful for stepping through the command's code.
#
# AUTHOR: Jacek Wielemborek, licensed under WTFPL.

prog=$1
shift
set -x
gdb "$prog" -ex "break main" -ex "r $*"
