#!/bin/sh

# Display the range for unpushed commits. Fails on errors. Works with git-svn.
#
# Example - count unpushed commits:
#
# git log --format=oneline "$(git unpushed-range 2>/dev/null)" 2>/dev/null | \
#   wc -l
#
# AUTHOR: Jacek Wielemborek, licensed under WTFPL.

CURRENT_BRANCH=`git rev-parse --abbrev-ref HEAD`
UNPUSHED_RANGE="$( git log --grep='git-svn-id' --format=oneline | head -n1 | cut -d' ' -f1 ).."
if [ "X${UNPUSHED_RANGE}X" == "X..X" ]; then
  UNPUSHED_RANGE="$( git log origin/$CURRENT_BRANCH..HEAD --reverse --format=oneline | head -n1 | cut -d' ' -f1 )^.."
fi

echo $UNPUSHED_RANGE
