#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Test

DESCRIPTION:

(say something about what this software does)

EXAMPLE USAGE:

REQUIREMENTS:

AUTHOR: Jacek "d33tah" Wielemborek, licensed under WTFPL
"""

"""
TODO:
"""

import argparse


class ChangeMe(object):

    def __init__(self, args):
        self.args = args

    def run(self):
        pass

if __name__ == '__main__':
    fmt = argparse.RawDescriptionHelpFormatter
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=fmt)
    # parser.add_argument('--arg1', required=True, help='arg1')
    args = parser.parse_args()
    ChangeMe(args).run()
