#!/usr/bin/python

# Counts the occurences of all lines from the standard input and prints in the
# order from most common to least.
#
# EXAMPLE:
#
# > dmesg | count-lines | head -n1
# 2:      [    0.000000] ACPI: Local APIC address 0xfee00000
#
# AUTHOR: Jacek Wielemborek, licensed under WTFPL.

from collections import defaultdict
import sys

if sys.stdin.isatty():
    sys.stderr.write("WARNING: stdin is a TTY. This is probably not what you "
                     "wanted.")
    sys.stderr.flush()

d = defaultdict(int)
import sys
while True:
  l = sys.stdin.readline()
  if l == '':
    break
  d[l.rstrip("\r\n")] += 1

items = reversed(sorted(d.items(), key=lambda x: x[1]))
for k, v in items:
  print("%s:\t%s" % (v, k))
