#!/bin/sh

# Preceeds each line with current date.
#
# EXAMPLE:
#
# > ping 127.0.0.1 | datify
# Mon Apr 20 01:35:43 CEST 2015: PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
# Mon Apr 20 01:35:43 CEST 2015: 64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.038 ms
# Mon Apr 20 01:35:44 CEST 2015: 64 bytes from 127.0.0.1: icmp_seq=2 ttl=64 time=0.038 ms
# Mon Apr 20 01:35:45 CEST 2015: 64 bytes from 127.0.0.1: icmp_seq=3 ttl=64 time=0.050 ms
# (...)
#
# AUTHOR: Jacek Wielemborek, licensed under WTFPL.

perl -pe '$|=1; $x = `date`; chomp $x; print "$x: "'
