#!/bin/bash

# Runs the given program in a GNU debugger session. Useful for easily jumping
# into the crashing command's code.
#
# AUTHOR: Jacek Wielemborek, licensed under WTFPL.

prog=$1
shift
set -x
gdb "$prog" -ex "r $*"
