#!/usr/bin/env python

"""
Performs a selected set of actions on a list of IPs/IP ranges.

Author: Jacek Wielemborek, licensed under WTFPL.
"""

import sys
import IPy
import argparse

def main(args):
    ips = []
    for line in sys.stdin:
        ips += [IPy.IP(line.rstrip(), make_net=True)]
    ipset = IPy.IPSet(ips)
    if args.optimize:
        ipset.optimize()
    if args.count:
        print(len(ipset))
    if not args.do_print:
        return
    for n in ipset:
        if args.iterate:
            for i in n:
                print(i)
        else:
            print(n)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--count', action='store_true')
    parser.add_argument('--print', action='store_true', dest='do_print')
    parser.add_argument('--iterate', action='store_true')
    parser.add_argument('--optimize', action='store_true')
    args = parser.parse_args()
    if args.iterate or args.optimize:
        args.do_print = True
    if not args.do_print and not args.count:
        sys.exit('ERROR: use at least one of --print and --count.')
    main(args)
